# Generated by Django 3.0.2 on 2020-01-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('color', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('condition', models.PositiveIntegerField(help_text='in Minutes')),
                ('used', models.CharField(choices=[('n', 'new'), ('u', 'used')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('founded', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(default='null', max_length=4),
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.TextField(null=True),
        ),
        migrations.RenameModel(
            old_name='Person',
            new_name='Founder',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='founders',
            field=models.ManyToManyField(blank=True, to='yamod.Founder'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.Country'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.Country'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yamod.Manufacturer'),
        ),
    ]
