# Generated by Django 3.0.2 on 2020-01-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0002_auto_20200105_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
