# Generated by Django 3.0.2 on 2020-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0003_auto_20200105_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='country',
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('v', 'very good'), ('g', 'good'), ('k', 'ok'), ('b', 'bad')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
