# Generated by Django 3.0.2 on 2020-01-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0004_auto_20200105_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
