# Generated by Django 3.0.2 on 2020-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0005_auto_20200105_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30),
        ),
    ]
