# Generated by Django 3.0.2 on 2020-01-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0006_auto_20200105_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(default='', max_length=30),
        ),
    ]
