# Generated by Django 3.0.2 on 2020-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0007_manufacturer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Country_mostSales',
            field=models.ManyToManyField(to='yamod.Country'),
        ),
    ]
