# Generated by Django 3.0.2 on 2020-01-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0008_car_country_mostsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Country_mostSales',
        ),
    ]
