# Generated by Django 3.0.2 on 2020-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0009_remove_car_country_mostsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='test',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
