# Generated by Django 3.0.2 on 2020-01-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0012_car_country_mostsales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='Country_mostSales',
            field=models.ManyToManyField(blank=True, to='yamod.Country'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='headquarters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='yamod.Country'),
        ),
    ]
